

version: '3'
services:
  postgres:
    image: ovi
    hostname: postgres
    command: bash -c "curl -O https://raw.githubusercontent.com/OviDanielB/app_help/master/pg.sql && sleep 60 && psql -U postgres -c \"CREATE DATABASE mongooseim;\" && psql -U postgres -q -d mongooseim -f pg.sql "
    ports:
      - "5432:5432"
  mongooseim:
    hostname: mongooseim-1
    image: mongooseim/mongooseim
    ports:
      - '5222:5222'
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - /Users/ovidiudanielbarba/Desktop/mongoose:/usr/lib/mongooseim
